plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.korea'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'com.google.guava:guava:31.1-jre' // guava
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa:4.1.0' // JPA
	implementation 'com.mysql:mysql-connector-j:9.4.0' // mySQL connect
   	implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5' // JWT
   	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: '3.2.4'
	
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	
	 
   	// https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl
   	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
   	// https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-gson
   	implementation group: 'io.jsonwebtoken', name: 'jjwt-gson', version: '0.11.5'
}

tasks.named('test') {
	useJUnitPlatform()
}
